title: "Swiftian - Create. Explore."
description: "Swiftian is a curated, interactive platform for learning Swift through creative coding projects, engaging storytelling, and rhythm-enhanced productivity."
url: "https://swiftian.com"
permalink: pretty
author: "Swiftian Team"

# Sitemap settings
plugins:
  - jekyll-sitemap

collections:
  languages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: "_languages"
    values:
      sitemap: true
      author: "Swiftian Team"
  - scope:
      path: ""
    values:
      sitemap: true
  - scope:
      type: languages
    values:
      sitemap: true
      layout: default
