title: "Swiftian - Create. Explore."
description: "Swiftian is a curated, interactive platform for learning Swift through creative coding projects, engaging storytelling, and rhythm-enhanced productivity."
url: "https://swiftian.com"
permalink: pretty
author: "Swiftian Team"

# Sitemap settings
plugins:
  - jekyll-sitemap

# SEO Optimization for Multilingual Support
defaults:
  - scope:
      path: "_languages"
    values:
      sitemap: true
      author: "Swiftian Team"

# SEO defaults for main pages
  - scope:
      path: ""
    values:
      sitemap: true

# Multilingual SEO default setting
defaults:
  - scope:
      type: languages
    values:
      sitemap: true
