title: "Swiftian - Learn to Code"
description: "Swiftian is a platform for learning Swift through interactive coding projects."
url: "https://swiftian.com"
permalink: pretty
author: "Swiftian Team"

# Sitemap settings
plugins:
  - jekyll-sitemap

# SEO Optimization for Multilingual Support
defaults:
  - scope:
      path: "ko/*"
    values:
      sitemap: true
  - scope:
      path: "en/*"
    values:
      sitemap: true

# Ensure Jekyll treats `ko/` as a normal page, not a collection
exclude:
  - languages
