title: "Swiftian - Learn to Code"
description: "Swiftian is a platform for learning Swift through interactive coding projects."
url: "https://swiftian.com"
permalink: pretty
author: "Swiftian Team"

# Sitemap settings
plugins:
  - jekyll-sitemap

# Define the 'languages' collection to process the _languages folder
collections:
  languages:
    output: true        # Output collection items as standalone pages
    permalink: /:path/   # This will use the file's relative path within _languages

# SEO Optimization for Multilingual Support
defaults:
  - scope:
      type: languages   # Apply defaults for all language items
    values:
      sitemap: true
