title: "Swiftian - Learn to Code"
description: "Swiftian is a platform for learning Swift through interactive coding projects."
url: "https://swiftian.com"
permalink: pretty
author: "Swiftian Team"

# Sitemap settings
plugins:
  - jekyll-sitemap

# Enable multilingual collections
collections:
  languages:
    output: true
    permalink: /:path/

# SEO Optimization for Multilingual Support
defaults:
  - scope:
      path: ""
      type: "languages"
    values:
      sitemap: true

# Generate hreflang tags for search engines
liquid:
  filters:
    - "append: 'hreflang', page.lang"
